server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.2.211:3306/cloud_user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


#
#        cluster-name: SH
#        namespace: dc5ea29a-cd90-442b-98bd-abbfbab9981b 命名空间
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#pattern:
#  dateformat: yyyy-MM-dd HH:mm:ss


#eureka:
#  client:
#    service-url:
#      defatulZone: http://127.0.0.1:10086/eureka
